language: node_js
node_js:
  - '12.13'
deploy:
  skip_cleanup: true
  provider: npm
  email: altay.aydemir@gmail.com
  api_key:
    secure: di/1U7T+VHlQDVDPwAi++29Ar3z89mF/dahe7ya3x3WmapU0xxEzV9QVeyXOGisrMMPEZeHC8qSO3f/mIWVM8y+mQ5g85Yhiu1qpELMMVPXmw3BX8dYuRNYFPnWr6gFz9+FMl9QNaSXpSAqxK5XPd3ra6+Au+SdbkGJv9UBpa64IzwYx65JEOkWposu5YtuZRxGkqJ0+Sc2ntBzPVVIX6uRGXFz1J0BhnzAhNd2RvJy6H8uk4PSxQjGtdWnf2bHiDCvi/7GhmzeqXFf4IjTPbqliMPGzSGazLXIeGwGy0JlNSGYSpcV0iuzCj5urLbOuMeNJKxYF255o8vFthAWEce3MGvcEm7j3wQW0vWCJd1nSPpapMe+89ZeUfuWIcDwuLk3cb70c7VOWTgLVpLexVMdKt6NJCXNYBQ9dM59kzduGzDO+jaPOVljXquHtdPp83VGg1gsmpzEvR8BN5h41xpMuc7oQm4x/but11EuKZo7e0h0iVEqPL9gRsgmfRXFjOahUdDbStspTkfIrPsmsXcWCR9xutrPsKoTt+5qL6JEM14Ml9EWipU3IpJ2uoj9vqwRh+oVNkqR/SJyhIJDBZTxzOnOGvEhBwK7OxqMFx5TQTAopx99Zg+0zEn6HlyMnQhWcWKS3DQSyDA4qigi4xB9cw9Z2g5vLEAAw38NwePk=
  on:
    tags: true
    repo: putdotio/prettier-config
